sudo: required

language: node_js

node_js:
  - "9"
  - "8"

services:
  - docker

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm integration
      node_js: "9"
      before_install:
        - docker-compose up --build -d
      script: 
        - echo "Running integration test on full stack agains $(node -v) ..."
        - docker-compose run api npm test

notifications:
  email:
    recipients:
    - filipmamic@hotmail.com
    on_success: change
    on_failure: always