sudo: required

language: node_js

node_js:
  - "9"

services:
  - docker

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: npm integration
      node_js: "9"
      before_install:
        - docker-compose up --build -d
      script: 
        - echo "Running integration test on full stack agains $(node -v) ..."
        - docker-compose exec api npm run integration-test

deploy:
  - provider: heroku
    api_key: "7c14838d-cecc-466e-9bd9-364734c41ed6"
    app: coffee-time-app

notifications:
  email:
    recipients:
    - filipmamic@hotmail.com
    on_success: change
    on_failure: always